source 'https://rubygems.org'
ruby '>= 2.3'

gem 'activesupport'
gem 'autoprefixer-rails'
gem 'colorize'
gem 'middleman', git: 'https://github.com/middleman/middleman.git', branch: '4.x'
gem 'middleman-autoprefixer'
gem 'nokogiri'
gem 'octokit'
gem 'sassc'
gem 'slim'
