#!/bin/sh
set -e

cd "$GIT_DIR/.."

# FIXME: workaround for Webpack < 5.61 on NodeJS > 16 and OpenSSL 3
# error:0308010C:digital envelope routines::unsupported
export NODE_OPTIONS=--openssl-legacy-provider

bundle install
npm install

# avoid "ArgumentError: invalid byte sequence in US-ASCII"
export RUBYOPT='-EUTF-8 -W0'

bundle exec ./update.rb
bundle exec middleman build
