#!/bin/sh
DEPLOY_DIR="/CHANGE/ME/"

function puts { echo "post-receive: $*"; }

export GEM_HOME=$(ruby -e 'puts Gem.user_dir')
PATH="$GEM_HOME/bin:$PATH"

read from to branch

if [ "$branch" != "refs/heads/master" ]; then
  puts "received branch '$branch', not deploying."
  exit 1
fi

GIT_WORK_TREE="$DEPLOY_DIR" git checkout -f master
puts "master at '$to' copied to '$DEPLOY_DIR'"

# avoid "ArgumentError: invalid byte sequence in US-ASCII"
export RUBYOPT=-EUTF-8

cd "$DEPLOY_DIR"
bundle
bundle exec ./update.rb
bundle exec middleman build

puts "Done!"
