#!/bin/sh
DEPLOY_DIR="/CHANGE/ME/"

function puts { echo "post-receive: $*" }

export GEM_HOME=$(ruby -e 'puts Gem.user_dir')
PATH="$GEM_HOME/bin:$PATH"

read from to branch

if [ "$branch" != "refs/heads/master" ]; then
  puts "post-receive: received branch '$branch', not deploying."
  exit 1
fi

GIT_WORK_TREE="$DEPLOY_DIR" git checkout -f master
puts "master at '$to' copied to '$DEPLOY_DIR'"

cd "$DEPLOY_DIR"
bundle
./update.rb
(cd public/stylesheets/sass; bourbon install)

thin stop 2> /dev/null

mv log/thin.log log/thin.log.old
RACK_ENV=production bundle exec thin start -d

sleep 2
cat log/thin.log

puts "Done!"
